/* const newDiv = document.createElement("div");
	newDiv.id = "kstemp";

	newDiv.innerHTML = `
		 <select id="ksDropdown">
        <option value="">Select an option</option>
		</select>
		`; */
		
/* 		document.getElementById("WIN_0_536998669").insertAdjacentHTML('beforeend', '<select id="ksDropdown">
        <option value="">Select an option</option>
		</select>'); 
*/
		
	var newElement = document.createElement("div");
		newElement.id = "wkst";
		newElement.style.position = "absolute";
		newElement.style.zIndex = "99999";
		newElement.style.top = "30px";
		newElement.style.left = "825px";
        newElement.innerHTML = "<select id='ksDropdown'>        <option value=''>Select KS</option>		</select>";
    //document.getElementById("WIN_0_536998669").appendChild(newElement);
	//document.body.appendChild(newElement);	
	document.getElementById('FormContainer').appendChild(newElement);
		//style="position: absolute; width: 200px; height: 200px; background-color: coral; z-index: 99999; top: 50px; left: 50px;"
		

	  const dropdown = document.getElementById('ksDropdown');

	  // Hardcoded options array
	  const options = [
		{ value: '', text: '----Erstmeldung----' },
		{ value: 'Dear Sir or Madam,\n\nWe have recognized a service disturbance on the above component and opened an incident ticket for this issue. Once the initial analysis is completed we will give you an exact description of the error. In accordance with the Service Level Agreement  (SLA) we will keep you informed of the current status and progress. For information or questions you can contact us at anytime. Please state the Ticket ID as reference.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'Proactive Erst' },
		{ value: 'Dear Sir or Madam,\n\nWith reference to the fault as reported by you, we have opened the above stated trouble ticket. This matter will be directly forwarded to the relevant service unit.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'Reactive Erst' },
		{ value: 'Dear Sir or Madam,\n\nWith reference to the fault reported by you, we have opened the above stated trouble ticket and have started our investigation.\n\nAs soon as we have an update available we will inform you accordingly.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'Reactive NP Erst' },
		{ value: 'Dear Sir or Madam,\n\nPlease be informed that we have proactively detected an outage affecting the following circuit:\n\nMAN Line ID: [full line ID]\nEnd points: [Standort A] - [Standort B]\n\nTherefore we have generated the current Trouble Ticket. The investigation is in progress, we will keep you informed about the proceedings regularly.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'BMAN Proactive Erst' },
		{ value: 'Dear Sir or Madam,\n\nWith reference to the fault reported by you for the below line, we have opened the above stated trouble ticket.\n\nMAN Line ID: [full line ID]\nEnd points: [Standort A] - [Standort B]\n\nThis matter has been directly forwarded to the relevant service unit.\n\nAs soon as we have an update available we will inform you accordingly.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'BMAN Reactive Erst' },
		{ value: 'Dear Sir or Madam,\n\nplease be informed, that we acknowledged a planned work for your service. Therefore we have opened this preventive maintenance ticket.\nThe necessary steps have already been initiated to deactivate the alarming for this site during the planned construction work to eliminate opening an incident ticket. Until the end of the works this ticket is kept on hold and we stop sending the customer status messages to you.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'Wartung opener' },
		{ value: '', text: '---------' },
		{ value: 'Dear Sir or Madam,\n\nWe would like to let you know that there is already an existing investigation ticket for this issue: _______.\n\nTherefore, until further updates received regarding the investigation, we will keep this ticket on hold and stop sending customer reports.\n\nAs soon as we receive an update, we will inform you accordingly.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'Related Ticket' },
		{ value: 'Dear Sir or Madam,\n\nPlease be advised that the appliances are still stable, the service is still working properly, however the alarm has reoccured, therefore we have reopened this trouble ticket. As we stated in our previous final report the alarm has been generated due to a synchronization error issue on the appliances, which did not affect the site.\nHowever in the next hours we are going to monitor the service to ensure its stability.\nDuring this time we are keeping this ticket on hold and we will stop sending customer reports.\nIn case we have an update available, we will inform you accordingly.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'Synchronization reopen' },
		{ value: 'Dear Sir or Madam,\n\nPlease be informed that for further troubleshooting we have forwarded this case to our second level team. As soon as we receive their expertise we will update you accordingly.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'Forwarded to 2nd lvl' },
		{ value: 'Dear Sir or Madam,\n\nPlease be informed that our second level unit is still in direct contact with the service provider. They are looking for a permanent solution to fix this issue. Once we have further details we will update you accordingly.\n\nBest regards\nDeutsche Telekom\nService Desk', text: '2nd lvl & provider working' },
		{ value: 'Dear Sir or Madam,\n\nPlease be informed that this outage is under investigation by the responsible service unit. We will update you as soon as we receive any further information.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'Forwarded to Provider' },
		{ value: 'Dear Sir or Madam,\n\nPlease be informed that our second level team is still making every effort in order to resolve the reported issue. We are still in contact with our second level and tracking their investigation. Once we receive new information we will update you accordingly, but until then we will stop sending customer status messages.\n\nBest regards\nDeutsche Telekom\nService Desk', text: '2nd lvl continue in NBH' },
		{ value: 'Dear Sir or Madam,\n\nPlease be informed that for further investigation we are waiting for the advise of our responsible team.\nAs this ticket is under internal clarification, until we receive a feedback we stop sending customer reports.\nAs soon as we receive any news, we will let you know.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'Internal clarification (waiting MGMT)' },
		{ value: 'Dear Sir or Madam,\n\nPlease be informed that our responsible service unit is still making every effort in order to resolve the reported issue. We are still in contact with our partner and tracking their investigation.\nAs soon as we have further information we will share it with you.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'Provider still working' },
		{ value: 'Dear Sir or Madam,\n\nPlease be informed that we have proactively detected that the secondary router is not reachable via its circuit, only through the cross LAN connection from the primary router, which is up and running stable and error free.\nThis issue has been reported to the responsible provider. As soon as we have an update, we will inform you accordingly.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'PRY up, BU down, Xlink OK' },
		{ value: 'Dear Sir or Madam,\n\nPlease be informed that we have proactively detected that the primary router is not reachable via its circuit, only through the cross LAN connection from the secondary router, which is up and running stable and error free.\nThis issue has been reported to the responsible provider. As soon as we have an update, we will inform you accordingly.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'PRY down, BU up, Xlink OK' },
		{ value: 'Dear Sir or Madam,\n\nPlease be informed that the issue has reoccurred therefore, we have reopened this trouble ticket. \nWe would like to inform you that this outage is under investigation by the responsible service unit. \n\nBest regards\nDeutsche Telekom\nService Desk', text: 'Issue has reoccurred' },
		{ value: 'Dear Sir or Madam,\n\nPlease follow related ticket … for updates regarding this incident. Until our investigation is concluded in that ticket we will stop sending customer reports. Thank you for your understanding.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'Related ticket 1' },
		{ value: 'Dear Sir or Madam,\n\nPlease be informed that the case is under investigation in the ticket … . Until our investigation is concluded in that ticket, we will stop sending customer messages.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'Related ticket 2' },
		{ value: '', text: '----COA----' },
		{ value: 'Dear Sir or Madam,\n\nWe would like to inform you that our device(s) is (are) not reachable on the location.\n\nBased on our documentation, the circuit connected to our device(s) is (are) customer owned; which means we are not responsible for the troubleshooting of the line issue.\nPlease contact your own local internet provider and let us know if you need further assistance from us.\n\nIn case you need assistance from us, make sure that you have rebooted (power cycle) our device and your internet provider onsite device. Please check the power status, and the cabling between the network elements.\nAlso please let us know the results of your service provider line investigation, the access hours of the site, and reachable local contact in case of technician dispatch.\n\nUntil your feedback we keep this ticket on hold and stop sending customer reports. \n\nBest regards\nDeutsche Telekom\nService Desk', text: 'COA link - Total outage' },
		{ value: 'Dear Sir or Madam,\n\nWe would like to inform you that one of the line provider links are down on the location.\n\nBased on our documentation, the circuit connected to our device is customer owned; which means we are not responsible for the troubleshooting of the line issue.\nPlease contact your own local internet provider and let us know if you need further assistance from us.\n\nIn case you need assistance from us, make sure that you have rebooted (power cycle) our device and your internet provider onsite device. Please check the power status, and the cabling between the network elements. \nAlso please let us know the results of your service provider line investigation, the access hours of the site, and reachable local contact in case of technician dispatch.\n\nUntil your feedback we keep this ticket on hold and stop sending customer reports.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'COA link down' },
		{ value: 'Dear Sir or Madam,\n\nWe would like to inform you that the internet line connected to the router is customer owned. Therefore, we would like to ask you to report the malfunction to your line provider and give us a feedback about it. Until your feedback we are placing this ticket on hold and we will stop sending customer reports. We are looking forward to hearing from you.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'COA Router' },
		{ value: '', text: '----No Update----' },
		{ value: 'Dear Sir or Madam,\n\nWe would like to report you that we have no new information on this case as of yet. Our responsible second level team/service provider is still working on this case, and we will inform you once they have sent us any new information.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'No update KS (BSKS1)' },
		{ value: 'Dear Sir or Madam,\n\nWe would like to inform you that we are still waiting for our responsible second level team/service provider to send us an update on this case. As soon as they do, we shall send you any new information.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'No update KS (BSKS2)' },
		{ value: 'Dear Sir or Madam,\n\nUnfortunately there is still no update available, this case is still being looked into by our responsible second level team/service provider. As soon as we get news we will inform you immediately.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'No update KS (BSKS3)' },
		{ value: '', text: '----Basic Check----' },
		{ value: 'Dear Sir or Madam,\n\nPlease be kindly informed, that we have proactively registered an issue on your service. The router(s) is (are) unreachable. Please inform us in case you have any information concerning maintenance work or activities affecting the power supply at the location. For further troubleshooting it is required to reboot the router(s) and modem(s) on site, check the LED status after and before the reload and also please check the cables if they are seated properly to the correct port. Please perform these actions and send us the opening hours of the site as well, in case of technical dispatch would be needed by our service partner.\nUntil your feedback we put our ticket on hold.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'CE power check' },
		{ value: 'Dear Sir or Madam,\n\nPlease be kindly informed, that we have proactively registered an issue on your service. The switch is unreachable. Please inform us in case you have any information concerning maintenance work or activities affecting the power supply at the location. For further troubleshooting it is required to reboot the switch on site, check the LED status after and before the reload and also please check the cables if they are seated properly to the correct port. Please perform these actions and send us the opening hours of the site as well, in case of technical dispatch would be needed by our service partner.\nUntil your feedback we put our ticket on hold.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'Switch power check' },
		{ value: 'Dear Sir or Madam,\n\nPlease be kindly informed, that we have proactively registered an issue on your service. The Aruba appliance(s) is (are) unreachable. Please inform us in case you have any information concerning maintenance work or activities affecting the power supply at the location. For further troubleshooting it is required to reboot the ISP modem(s) on site, check the LED status after and before the reload and also please check the cables if they are seated properly to the correct port. Please perform these actions and send us the opening hours of the site as well, in case of technical dispatch would be needed by our service partner.Until your feedback we put our ticket on hold.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'Aruba power check' },
		{ value: 'Dear Sir or Madam,\n\nPlease be kindly informed, that we have proactively registered an issue on your service. The above mentioned device unreachable. Please inform us in case you have any information concerning maintenance work or activities affecting the power supply at the location. For further troubleshooting it is required to power cycle the device on site, check the LED status after and before the reload and also please check the cables if they are seated properly to the correct port. Please perform these actions and send us the opening hours of the site as well, in case of technical dispatch would be needed by our service partner.\nUntil your feedback we put our ticket on hold.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'General power check' },
		{ value: 'Dear Sir or Madam,\n\nPlease be kindly informed, that we have proactively registered an issue on your service. The device(s) is (are) unreachable. Please inform us in case you have any information concerning maintenance work or activities affecting the power supply at the location. For further troubleshooting it is required to check the power status of the equipment and cables if they are seated properly to the correct port. Please perform these actions and send us the opening hours of the site as well, in case of technical dispatch would be needed by our service partner.\nUntil your feedback we put our ticket on hold.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'General power check (no reboot)' },
		{ value: '', text: '---------' },
		{ value: 'Dear Sir or Madam,\n\nWe would like to inform you that the line is up and running stable again. We will monitor the line for quality reasons in the coming hours and wait for final confirmation from the responsible service unit that no further outages are expected. As soon as we have the results, we will update you.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'Monitoring, Further outages' },
		{ value: 'Dear Sir or Madam,\n\nWe would like to inform you that the line is up and running stable again. In the next hours we are going to monitor the line for quality reasons and we are waiting for the reason for outage from our responsible service partner. During this time we will keep our ticket on hold.  As soon as we have the results, we will update you.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'Monitoring, waiting for RFO' },
		{ value: 'Dear Sir or Madam,\n\nPlease be advised that the appliances are stable, the service is working properly. The alarm has been generated due to a synchronization error issue on the appliances, which did not affect the site.\nHowever in the next hours we are going to monitor the service to ensure its stability.\nDuring this time we are keeping this ticket on hold and we will stop sending customer reports.\nIn case we have an update available, we will inform you accordingly. \n\nBest regards\nDeutsche Telekom\nService Desk', text: 'Sync issue -> monitoring' },
		{ value: 'Dear Sir or Madam,\n\nWe would like to inform you that we have received the information from our responsible service provider, that\n\nAs soon as we have an update available we will inform you accordingly.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'Feedback from provider' },
		{ value: 'Dear Sir or Madam,\n\nWe would like to inform you that we have received the information from our responsible 2nd level team, that\n\nAs soon as we have an update available we will inform you accordingly.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'Feedback from 2nd lvl' },
		{ value: 'Dear Sir or Madam,\n\nPlease be informed that our responsible service unit is still making every effort in order to resolve the reported issue. We are still in contact with our partner and tracking their investigation.\n\nWe have also escalated this case towards the service provider, in order to speed up their investigation.\n\nAs soon as we have further information we will share it with you.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'Provider still working + escalation' },
		{ value: 'Dear Sir or Madam,\n\nWe would like to inform you that the line is completely over utilized.\n\nYou may turn to your management for a bandwidth upgrade in order to prevent the overutilization of these lines.\n\nFurthermore, we can perform an IP-Accounting (Top Talkers report) in order to find out what is generating this much traffic on the line. If you would like to request this, please note that we need a time window for this action.\n\nPlease advise how you would like to proceed further.\nUntil your feedback, this ticket will be on hold.\nIf we do not receive any reply from your side in the next 5 working days, this ticket will be automatically closed.\n\nBest regards\nDeutsche Telekom\nService Desk', text: '2nd lvl Overutilization 1Strike' },
		{ value: 'Dear Sir or Madam,\n\nWe would like to inform you that we have investigated the reason for the outage with our responsible service unit. In cooperation with them, we have carried out specific tests and checked all of the components supported by our service department.\nThese tests have been proven successful and no errors or faults were detected on any of the equipment supported by us or by our service provider. Despite of a deeper investigation the reason for outage is unknown.\nShould you experience further outages - please do not hesitate to inform us.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'Line Overloaded - Overutilization' },
		{ value: 'Dear Sir or Madam,\n\nWe would like to inform you that the responsible service provider is still looking into the issue.\nUnfortunately, they were unable to reach a permanent solution so far. \n\nIn order to speed up the resolution we have escalated this case.\n\nWe are closely following their progress in the investigation and when we receive an update from their side you will be immediately informed.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'Escalation' },
		
		{ value: '', text: '----Closing----' },
		{ value: 'Dear Sir or Madam,\n\nPlease be advised that the fault is no longer visible, and the service is up and running stable since XclosureTimeX. This location is now reachable via our network management system.\n\nIn the next 4 hours we are going to monitor the service for stability. If no issue appears during this time our ticket will automatically be closed.\n\nShould you experience further outages - please do not hesitate to inform us and we will investigate further.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'Closing 4h monitor'  },
		{ value: 'Dear Sir or Madam,\n\nPlease be informed that service is still working properly since XclosureTimeX. The outage reason is still unknown for us and we are in contact with our provider to identify the root cause. As soon as we receive it we will share it with you.\n\nAs the service is stable we are closing our trouble ticket in accordance with our Service Level Agreement.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'Closing without RFO' },
		{ value: 'Dear Sir or Madam,\n\nPlease be informed that the connection has been stabilized and working properly since XclosureTimeX. The outage was caused by a power supply failure on site.\n\nTherefore we are closing this ticket in accordance with our Service Level Agreement.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'Power outage' },
		{ value: 'Dear Sir or Madam,\n\nPlease be advised that the appliances are stable, the service is working properly. The alarm has been generated due to a synchronization error issue on the appliances, which did not affect the site.\nTherefore we are closing our trouble ticket.\nIf you need any further assistance or information from us, please let us know. \n\nBest regards\nDeutsche Telekom\nService Desk', text: 'Sync issue -> closing' },
		{ value: 'Dear Sir or Madam,\n\nWe would like to inform you that we have investigated the reason for the outage with our responsible service unit. In cooperation with them, we have carried out specific tests and checked all of the components supported by our service department.\nThese tests have been proven successful and no errors or faults were detected on any of the equipment supported by us or by our service provider. Despite of a deeper investigation the reason for outage is unknown.\nShould you experience further outages - please do not hesitate to inform us.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'No RFO' },
		{ value: 'Dear Sir or Madam,\n\nwe would like to inform you, that this location is now reachable again via our network management system. The maintenance work has been successfully finished. The alarming is enabled again for the site. In accordance with the terms of our service level agreement we are now closing this ticket.\n\nBest regards\nDeutsche Telekom\nService Desk', text: 'Wartung closure - Abschlussmeldung' },
		{ value: 'Dear Sir or Madam,\n\nWe would like to let you know that as we did not receive any feedback from you in the last five days regarding this incident, we assume that the issue is resolved. For this reason we are resolving our ticket on our side.\n\nIf you need any further assistance or information from us, please let us know.\n\nBest regards\n', text: '1 Strike Close' },
		// Converter: https://codepen.io/jsnelders/pen/qBByqQy
		//{ value: '', text: '---------' },
	  ];

	  // Populate dropdown with options
	  options.forEach(option => {
		const opt = document.createElement('option');
		opt.value = option.value;
		opt.textContent = option.text;
		dropdown.appendChild(opt);
	  });
	  
    document.getElementById("ksDropdown").addEventListener("change", function() {
        const selectedOption = document.getElementById("ksDropdown").value;

        document.getElementById("arid_WIN_0_536871782").value = selectedOption;
		navigator.clipboard.writeText(selectedOption);
		
		
		var textAreaNotiz = document.getElementById("arid_WIN_0_536871782");
		simulateUserInteraction(textAreaNotiz);
		
    });



